### ISSUE TITLE
Updates are so slow

### ISSUE THREAD

**Issue by gyllen** [keechma/keechma#14]
Im a part of one of the more exciting webprojects out on the web today and we are thinking about upgrading to keechma. However the updates are so slow to the framework. I thought you were working full time on it now?

Have you taken a couple of weeks of vacation?

**Comment by retro** [comment]
Hi @gyllen 

Yes, the updates are a bit slow because I worked on one of the more exciting webprojects out on the web until Oct 1st, so I needed a week to recuperate :).

Regarding the Keechma updates and plans here's the rough plan for the features that should land in the next few months (I still haven't decided which of these are going into the Keechma core, and which are going to be separate projects):
1. Extract routing from the [application state manager](https://github.com/keechma/keechma/blob/master/src/keechma/app_state.cljs) - I want to be able to support the following routing "backends":
   - Hashchange (currently implemented)
   - Push State
   - [React Native Navigator (experimental version)](https://facebook.github.io/react-native/docs/navigation.html#navigationexperimental)
2. Devtools (similar to https://github.com/gaearon/redux-devtools)
3. Convenience / Omakase version of Keechma - set of libraries and APIs that I personally use with Keechma - a very opinionated stack based on Keechma

All of this should be followed with a lot of new documentation and after that release 1.0 will happen.

**Comment by gyllen** [comment]
Closing issue are so slooow
