### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by davidsavoie1** [keechma/keechma#34]
I’ve recently discovered your framework and I must say that it seems to be a very good fit with the type of software I’m developping. I wonder however if it is still actively maintained and used. Comments and updates seem to date from more than a year ago and the package is not at 1.0 yet. I don’t want to be pushy, but I’d need to know if I could rely on it in the future before jumping on board. Thanks a lot and happy New Year!

**Comment by retro** [comment]
@davidsavoie1 thank you for your interest in keechma. Keechma is very much alive and we're building apps every day with it.

The biggest reason why the development seems to be slowed down is the amount of work I've been doing for the last 6 months. I've started working as a CTO in https://verybigthings.com where we're building most of the apps with keechma - we've released half a dozen projects in this time.

Great thing about it is that keechma is already very much battle tested and ready. Bad thing is that working on the things like docs and examples is suffering because of the lack of time. Hopefully as I'll have more time to work on it on 2019.

If you have any questions you can also reach me on the Clojurians slack - #keechma channel - or email me directly at konjevic@gmail.com

**Comment by davidsavoie1** [comment]
Great! I thank you very much for the fast answer! That alone is a good indicator of the project’s aliveness to me!

I totally understand your situation and overwhelm. I’ll try to give Keechma a shot soon. If I ever become proficient with it someday, maybe I could help out with documentation!
