### ISSUE TITLE
How to do forms with high number of inputs in keechma

### ISSUE THREAD

**Issue by ingesolvoll** [keechma/keechma#4]
The documentation for keechma is amazing, but I'm missing good examples for large scale forms. I need a way to update the global atom when an input field in the form changes value. From what I can see, there are a couple of options:
- Do `(ui/send-command ctx :on-change {:path [:customer :name] :value "What I just typed"})`. The message system does not seem like a natural fit for lots of simple change messages from many text fields. And it's a bit on the verbose side for the code.
- Use a local atom that is sent in its entirety on submit. Not a super fan of this either, for a big form I would like to keep the data in the global app atom.
- Let subscriptions return cursors instead of reactions, and then have the input field reset/swap the cursor on change. That breaks the rule in Keechma of only letting controllers mutate the state.

For now, I chose the third as the best trade off for me. Not super comfortable about it, though. Do you have some suggestions or existing examples?

Again, thanks for some very interesting architecture ideas :)

**Comment by retro** [comment]
I agree that there should be a better solution for working with forms. Personally I use the local atom most of the time, but I can see that it might not be the best solution for everyone.

I've been thinking about forms and Keechma for some time now, and I would like to solve that issue in a good way, but unfortunately I didn't event start on it yet. So I would say that for now do whatever works for you, until there is a better solution.

I will keep this issue open to track the form lib progress. Here is some of my previous work on the form libraries (in JavaScript) which I'll use as inspiration:
- https://github.com/retro/can-form
- https://github.com/retro/FormBinder
- https://github.com/canjs/canjs/issues/1111#issuecomment-54894365

Please let me know what features are most important for you when working with forms, so I can ensure that they are implemented.

**Comment by ingesolvoll** [comment]
I think having the subscription return a cursor works fairly well. It still provides some encapsulation in that the component only gets access to the sub tree that is to be edited by the form. So part of the keechma benefit is there.

As for the "only controllers can mutate state", I guess there must be some kind of trade off for forms anyway. You don't really want keechma to be too specific about how to make UI components either?

I made some constructs for validation and generic form fields on my last project that ended up quite nice, based on a base cursor and path vectors along with configuration objects for each field. Using that I was able to share input field metadata with server app, to provide shared server/client validation in CLJC, shared code for PDF and HTML output, things like that. I really liked to have a system where field metadata was clearly separated from presentation.

Not sure if a UI framework like Keechma should be too opiniated about such an approach, maybe better to provide some nice foundation to enable solid custom architectures? Or maybe an optional default/recommended approach?

**Comment by retro** [comment]
I have started the work on this in the https://github.com/keechma/forms repo, and now I'm at the point where my next step is to provide the glue code for Keechma.

I have implemented validator engine and dirty fields tracker, and since there are no docs ATM if you want to take a look at the API, check the tests folder: https://github.com/keechma/forms/tree/master/test/forms/test .

I think that the nicest validator feature is the ability to compose and nest validators which will allow you to easily share them across forms - [nested validators](https://github.com/keechma/forms/blob/master/test/forms/test/validator.cljs#L77-L87), [composed validators](https://github.com/keechma/forms/blob/master/test/forms/test/validator.cljs#L55-L75).  

When fully implemented a "form" would be something that does the following:
- it would have an internal state atom in which it would track data, dirty fields and errors
- it could do a live validation (which would only change the errors field in the state atom)
- it could call a fn on commit (when user submits the form)
- it could keep track of the external errors (for instance errors that came from your server), these need to be tracked separately because they shouldn't affect the `is-valid?` state of the form, since you can't be sure if the current changes cleared those errors

## Keechma Integration

I would like Keechma to have a default good way to deal with the forms, but I would also like to avoid adding too much stuff into the core. This is what I have so far (regarding the API design):

``` clojure
;; Define a form with a validator, returns a "mounting" fn
(def user-form
  (form/constructor
   (validator {:username [not-nil]
               :password [not-nil]
               :email [not-nil is-email]})))

(defrecord UserController []
  controller/IController
  (handler [_ app-db-atom in-chan _]
    ;; create a form "instance
    (let [new-user-form (user-form
                         {:username nil :password nil :email nil} ;; Init form data
                         {:on-commit (fn []) ;; form options
                          :auto-validate true})]
      ;; Save form in the app-state
      (swap! @app-db-atom assoc-in [:forms :new-user] new-user-form))))

;; Forms are returned from the subscriptions
(defn user-form-subscription [app-state]
  (reaction
   (get-in @app-state [:forms :new-user])))

(defn form-render [ctx]
  (fn []
    ;; Retreive the form, form state and form errors
    (let [user-form @(ui/subscription ctx :user-form-subscription)
          user-form-state (form/state user-form) ;; returns atom
          user-form-errors @(form/errors user-form)]
      [:div.form-input
       "Username"
       ;; On change swap! data in the form state atom
       [:input {:on-change #(swap! assoc user-form-state :username (.. % -target -value))}]
       ;; Show errors if they exist
       (when (:username user-form-errors)
         [:div.errors (clojure.string/join "," (:username user-form-errors))])]
      ;; Commit the form on button click
      [:button {:on-click #(form/commit! user-form)} "Save User"])))
```

### Pros and cons of this design

#### Pros:
- implementation can be external, no code needs to be added to the Keechma core
- forms are retrieved through the subscriptions which is familiar to the Keechma users
- it would allow easy integration with the UI form libs like https://github.com/reagent-project/reagent-forms/

#### Cons:
- forms are retrieved through the subscriptions which feels dirty
- API is a bit ugly and boilerplatey
- Forms use internal atom to keep track of the state, instead of saving to the app state atom, only the reference to the form is saved in the app state atom - _this is not a problem for me, as I believe that the form state shouldn't be **shared** until it's in valid state or commited by user_

Currently I'm leaning to this API because it will take the least time to implement and we can reuse the existing infrastructure to work with them.

**Please let me know what you think about this**

@ingesolvoll ^

**Comment by ingesolvoll** [comment]
Looks clean enough to me!

I like the idea of doing this as a separate library. Having a smooth standard way of doing forms with validation is really nice, but there will be situations where the shoe doesn't fit. In those cases, I want to be able to skip the standard abstractions and roll my own. 

I'm not too worried about the amount of boilerplate so far.

For validation, I think the following is important:
- Validation rules are expressed as pure predicate functions
- Validation rule sets are pure maps reusable outside framework
- Validation messages are easily configurable
